### PR TITLE
feat: add open timeout as configurable option

### PR DESCRIPTION
**Pull request by sserghei**
config faraday timeout through config gem options

### CODE REVIEW

**Comment by sserghei** [comment]
@mdibaiee please take a look

**Comment by mdibaiee** [comment]
Hi @sserghei, sorry for the late reply.
As you may already know our SDKs are auto-generated using OpenAPI-generator.tech, which means these changes will be overriden every time we re-generate our SDKs, which we do every time there is a change / addition in the API.

Have you found a way to change this value without modifying the SDK's code? (perhaps a way to access the connection from your own code?)

**Comment by sserghei** [comment]
@mdibaiee  90% probability what first request to any api endpoint with SDK will be dropped, so right now only monkey patch save me)))
It would be nice to configure  open_timeout. Default value for Faraday is 2 seconds, right now i use value with 10 seconds.

**Comment by fcibecchini** [comment]
Closing for inactivity.

**Pull request closed without merging**
